### ISSUE TITLE
导出postman不支持 Pre-request Script与Tests吗

### ISSUE THREAD

**Issue by wxibm333** [tangcent/easy-yapi#188]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tangcent** [comment]
目前没有.
我自己一直用 http://easyyapi.com/documents/call.html

---

看了下,这个实现不难.
我会尝试增加两条规则来配置.

**Comment by tangcent** [comment]
Patch with #190 : [easy-yapi.1.9.4.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4606014/easy-yapi.1.9.4.0.183.0.jar.zip)
Download and unzip it. Install to IDEA.

---


- Try config like this:

``````properties

postman.prerequest=```
var a = "1";
var b = "1";
```
postman.test=```
var a = "1";
var b = "1";
```
``````

---

Please reopen the issue if you have any trouble

**Comment by wxibm333** [comment]
@tangcent 谢谢你的回复，我想问下，新增这个支持条件选择吗，比如配置的test代码块只想配置到登陆接口，获取token，然后将token设置成全局变量，提供给其他接口使用；其余接口不需要这个test

**Comment by tangcent** [comment]
see http://easyyapi.com/setting/config-rule.html
`postman.prerequest`和`postman.test`的上下文都是`method`.

---

***示例***

- 假如你有如下类:

```java
package com.itangcent.common.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

/**
 * 声明接口为公开接口
 */
@Documented
@Retention(RUNTIME)
@Target({TYPE, METHOD})
public @interface Public {
}

```

- 你可以尝试
``````
postman.prerequest[!@com.itangcent.common.annotation.Public]=```
var a = "1";
var b = "1";
```
``````

- ctrl:

```java

/**
 * 用户相关
 *
 * @module user
 */
@RestController
@RequestMapping(value = "user")
public class UserCtrl extends BaseController {

    /**
     * 打个招呼
     */
    @Public
    @RequestMapping(value = "/index")
    public String greeting() {
        return "hello world";
    }

    /**
     * 更新用户名
     *
     * @param id      用户id
     * @param newName 新的用户名
     * @param slogon  个人签名
     * @deprecated 改用{@link #update(UserInfo)}
     */
    @RequestMapping(value = "/set", method = RequestMethod.PUT)
    public Object set(long id,
                      @RequestParam String newName,
                      @RequestParam(required = false, defaultValue = "haha") String slogon,
                      @RequestParam(required = false, defaultValue = "10") long times) {
        ...
        return Result.success(userInfo);
    }
}
```

---

具体条件根据你的项目来写.

**Comment by xuguoqin** [comment]
配置的scripts不能针对collections为结构吗，现在的效果是每个接口都生成了脚本，我的脚本都是一样的，后面改起来可能会很麻烦 ，可以考虑下嘛@tangcent

**Comment by tangcent** [comment]
@xuguoqin good idea.

see #225

**Comment by tangcent** [comment]
@xuguoqin  
Patch with #226 : [easy-yapi.1.9.9.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/5002190/easy-yapi.1.9.9.0.183.0.jar.zip)

Download and unzip it. Install to IDEA.

---

- Try config like this:

``````properties

class.postman.prerequest=```
var a = "1";
var b = "1";
```
class.postman.test=```
var a = "1";
var b = "1";
```
``````

**Comment by xuguoqin** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tangcent/easy-yapi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 晚上11:25
收件人:&nbsp;"tangcent/easy-yapi"<easy-yapi@noreply.github.com&gt;;
抄送:&nbsp;"努力，奋斗!"<775275027@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tangcent/easy-yapi] 导出postman不支持 Pre-request Script与Tests吗 (#188)





 
@xuguoqin
 Patch with #226 : easy-yapi.1.9.9.0.183.0.jar.zip
 
Download and unzip it. Install to IDEA.
 
  
Try config like this:
  class.postman.prerequest=``` var a = "1"; var b = "1"; ``` class.postman.test=``` var a = "1"; var b = "1"; ```
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.




thank you
